// Central icon registry — never hardcode icon name strings in components.
// Usage: import { Icons } from '@/lib/icons'; then <Icon name={Icons.home} />

export const Icons = {
  // ── Navigation (student-app bottom nav) ──
  home:            'home',
  homeActive:      'home',
  subjects:        'menu_book',
  subjectsActive:  'menu_book',
  tests:           'assignment',
  testsActive:     'assignment',
  doubts:          'forum',
  doubtsActive:    'forum',
  profile:         'person',
  profileActive:   'person',

  // ── Navigation (admin-app sidebar) ──
  dashboard:       'dashboard',
  content:         'library_books',
  students:        'group',
  questions:       'quiz',
  doubtQueue:      'support_agent',

  // ── Common actions ──
  back:            'arrow_back',
  forward:         'arrow_forward',
  close:           'close',
  menu:            'menu',
  search:          'search',
  add:             'add',
  edit:            'edit',
  delete:          'delete',
  save:            'check',
  share:           'share',
  download:        'download',
  upload:          'upload',
  filter:          'tune',
  sort:            'swap_vert',
  refresh:         'refresh',
  more:            'more_vert',

  // ── Test / quiz ──
  timer:           'timer',
  timerOff:        'timer_off',
  play:            'play_arrow',
  pause:           'pause',
  stop:            'stop',
  skip:            'skip_next',
  check:           'check_circle',
  wrong:           'cancel',
  skipped:         'remove_circle',
  palette:         'grid_view',
  submit:          'send',
  review:          'rate_review',
  explanation:     'lightbulb',
  quiz:            'quiz',
  score:           'scoreboard',

  // ── Content ──
  video:           'play_circle',
  pdf:             'picture_as_pdf',
  notes:           'description',
  chapter:         'auto_stories',
  lock:            'lock',
  unlock:          'lock_open',
  complete:        'task_alt',
  progress:        'stacked_bar_chart',

  // ── Legacy content keys (backward compat) ──
  videoLesson:     'smart_display',
  lesson:          'play_lesson',
  note:            'sticky_note_2',
  book:            'menu_book',
  replay:          'replay',
  clock:           'schedule',
  checkCircle:     'check_circle',

  // ── User / auth ──
  google:          'g_mobiledata',
  phone:           'phone',
  otp:             'pin',
  logout:          'logout',
  settings:        'settings',
  notification:    'notifications',
  notificationOff: 'notifications_off',
  notifications:   'notifications',
  avatar:          'account_circle',
  camera:          'photo_camera',
  email:           'mail',
  school:          'school',

  // ── Subscription / payment ──
  premium:         'workspace_premium',
  crown:           'workspace_premium',
  payment:         'payment',
  receipt:         'receipt_long',
  star:            'star',
  diamond:         'diamond',
  sparkle:         'auto_awesome',

  // ── Feedback ──
  success:         'check_circle',
  error:           'error',
  warning:         'warning',
  info:            'info',
  doubt:           'help',
  answer:          'mark_chat_read',
  help:            'help',

  // ── Misc ──
  target:          'my_location',
  growth:          'trending_up',
  revenue:         'currency_rupee',
  users:           'group',
  streak:          'local_fire_department',
  trophy:          'emoji_events',
  chart:           'bar_chart',
  calendar:        'calendar_today',
  time:            'schedule',
  visibility:      'visibility',
  visibilityOff:   'visibility_off',
  send:            'send',
  image:           'image',
  attach:          'attach_file',
  resolve:         'task_alt',
  pending:         'pending',
  link:            'link',
  copy:            'content_copy',
  loading:         'progress_activity',
  empty:           'inbox',
  location:        'location_on',
  rank:            'leaderboard',
  badge:           'military_tech',
} as const

export type IconName = keyof typeof Icons
